# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "node-1",
        :type => "master",
        :box => "ubuntu/bionic64",
        :box_version => "20191121.0.0",
        :eth1 => "192.168.205.10",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-2",
        :type => "master",
        :box => "ubuntu/bionic64",
        :box_version => "20191121.0.0",
        :eth1 => "192.168.205.11",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-3",
        :type => "master",
        :box => "ubuntu/bionic64",
        :box_version => "20191121.0.0",
        :eth1 => "192.168.205.12",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-4",
        :type => "node",
        :box => "ubuntu/bionic64",
        :box_version => "20191121.0.0",
        :eth1 => "192.168.205.13",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-5",
        :type => "node",
        :box => "ubuntu/bionic64",
        :box_version => "20191121.0.0",
        :eth1 => "192.168.205.14",
        :mem => "4048",
        :cpu => "4"
    }
]


Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]
            config.vm.network "forwarded_port", guest: 22, host: 2200, host_ip: "203.250.77.140", auto_correct: true
	    config.vm.synced_folder "~/etcdWebVM/share", "/home/vagrant/share"

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--groups", "/etcdWeb"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end
	end
    end
end 

